[generate.contract]
description = "Generate a new smart contract for existing project"
path = ".algokit/generators/create_contract"

[generate.env-file]
description = "Generate a new generic or Algorand network specific .env file"
path = ".algokit/generators/create_env_file"

[project.run]
audit-teal = { commands = [
    'algokit task analyze artifacts --recursive --force --exclude rekey-to --exclude is-updatable --exclude missing-fee-check --exclude is-deletable --exclude can-close-asset --exclude can-close-account --exclude unprotected-deletable --exclude unprotected-updatable',
], description = 'Audit TEAL files' }
[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "placement-verification"

[project.build]
command = "python compile_all_contracts.py"

[project.deploy]
command = "backend\\.venv\\Scripts\\python.exe backend/scripts/deploy_contract.py"
environment_secrets = [
    "ALGOD_TOKEN",
    "ALGOD_SERVER",
    "ALGOD_PORT",
    "ALGOD_MNEMONIC"
]
